#!/usr/bin/env python3
"""Verify an evidence pack: regenerate one Evalwarden integrity card from the
pack's public inputs alone, and check it against the pack's pinned hashes.

Usage:
    python3 verify_pack.py evidence-pack.json [--work-dir /tmp/ep_work]

A stranger runs this on a fresh machine with nothing but the pack file.
Exit 0: every check passed (kill criterion: PASS).
Exit 1: any check failed, with the failing check named.
Stdlib only.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

UA = {"User-Agent": "evidence-registry-verifier/1.0"}


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def canon_json(obj) -> bytes:
    return json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")


def get(url: str, timeout: int = 120, retries: int = 3) -> bytes:
    """Fetch a URL with retries: a stranger-run verifier must survive transient
    network flakiness rather than failing the whole regeneration on one timeout."""
    last: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read()
        except Exception as exc:  # noqa: BLE001 - retry transient failures
            last = exc
            if attempt < retries - 1:
                time.sleep(2 ** attempt)
    raise RuntimeError(f"fetch failed after {retries} attempts: {url}: {last}")


def canonicalize_card(html: str) -> str:
    """Apply the pack's canonicalization rule: strip generation timestamps.

    Two substitutions, both mechanical:
    1. <footer>...</footer> (carries "Generated by evalwarden X.Y.Z, <ts>") -> <footer></footer>
    2. The methodology-table "Generated" row's timestamp cell -> TIMESTAMP
    The harness version string is deliberately KEPT: the pack pins the exact
    version, so a version mismatch must fail the check, not be normalized away.
    """
    html = re.sub(r"<footer>.*?</footer>", "<footer></footer>", html, flags=re.S)
    html = re.sub(
        r"(<tr><th>Generated</th><td>)\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC(</td></tr>)",
        r"\1TIMESTAMP\2",
        html,
    )
    return html


def check(name: str, ok: bool, detail: str = "") -> bool:
    print(("PASS " if ok else "FAIL ") + name + (f" -- {detail}" if detail else ""))
    return ok


def verify_task_definition_git(inp: dict) -> bool:
    pin = inp["pin"]
    m = re.match(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?$", inp["location"])
    if not m:
        return check("input:task_definition reachable", False, "location is not a github repo URL")
    owner, repo = m.group(1), m.group(2)
    url = f"https://api.github.com/repos/{owner}/{repo}/commits/{pin['commit']}"
    try:
        data = json.loads(get(url))
        ok = data.get("sha", "").startswith(pin["commit"][:12])
        return check("input:task_definition pin resolves", ok, f"{owner}/{repo}@{pin['commit'][:12]}")
    except Exception as exc:  # noqa: BLE001
        return check("input:task_definition pin resolves", False, str(exc)[:100])


def fetch_jsonl_head(url: str, want: int) -> list[str]:
    buf, offset = b"", 0
    for _ in range(12):
        req = urllib.request.Request(
            url, headers={**UA, "Range": f"bytes={offset}-{offset + 2_000_000 - 1}"}
        )
        data = None
        last: Exception | None = None
        for attempt in range(3):
            try:
                with urllib.request.urlopen(req, timeout=90) as resp:
                    data = resp.read()
                break
            except Exception as exc:  # noqa: BLE001 - retry transient failures
                last = exc
                time.sleep(2 ** attempt)
        if data is None:
            raise RuntimeError(f"dataset download failed after 3 attempts at offset {offset}: {last}")
        if not data:
            break
        buf += data
        offset += len(data)
        complete = [ln for ln in buf.decode("utf-8", errors="replace").splitlines()
                    if ln.strip().endswith("}")]
        if len(complete) >= want:
            return complete[:want]
        if len(data) < 2_000_000:
            break
    text = buf.decode("utf-8", errors="replace")
    return [ln for ln in text.splitlines() if ln.strip().endswith("}")][:want]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("pack", help="Path to evidence-pack.json")
    ap.add_argument("--work-dir", default=None, help="Fresh working directory")
    args = ap.parse_args()

    pack = json.loads(Path(args.pack).read_text(encoding="utf-8"))
    ok = True

    ok &= check("schema version", pack.get("schema_version") == "evidence-pack-v1",
                pack.get("schema_version", "missing"))

    work = Path(args.work_dir) if args.work_dir else Path.cwd() / "ep_work"
    if work.exists():
        shutil.rmtree(work)
    work.mkdir(parents=True)

    inputs = {i["role"]: i for i in pack["inputs"]}
    ok &= check("all inputs public", all(i.get("public") is True for i in pack["inputs"]))

    # 1. Task-definition pin resolves (human-auditable link).
    ok &= verify_task_definition_git(inputs["task_definition"])

    # 2. Dataset sample: re-fetch, hash exactly the consumed records.
    # Retried on mismatch: CDN edges can transiently serve byte-different but
    # value-identical serializations; persistent mismatch means real drift.
    ds = inputs["dataset_sample"]
    ds_hash, ds_n, ds_ok = "", 0, False
    for _ in range(3):
        lines = fetch_jsonl_head(ds["location"], 12)
        ds_hash = sha256_bytes(canon_json(lines))
        ds_n = len(lines)
        if ds_hash == ds["pin"]["content_sha256"]:
            ds_ok = True
            break
        time.sleep(2)
    ok &= check("input:dataset_sample content hash", ds_ok,
                f"got {ds_hash[:12]}, want {ds['pin']['content_sha256'][:12]} "
                f"({ds_n} records)")

    # 3. Builder script: byte-identical.
    b = inputs["builder"]
    builder_bytes = get(b["location"])
    ok &= check("input:builder content hash",
                sha256_bytes(builder_bytes) == b["pin"]["content_sha256"])
    builder_path = work / "build_real_cards.py"
    builder_path.write_bytes(builder_bytes)

    # 4. Rebuild the artifact with the pinned builder.
    spec = importlib.util.spec_from_file_location("builder", builder_path)
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    artifact_dir = builder.build_healthbench(work / "artifacts")

    manifest_files = {f.name: sha256_bytes(f.read_bytes())
                      for f in sorted(artifact_dir.iterdir()) if f.is_file()}
    manifest_hash = sha256_bytes(canon_json(manifest_files))
    tm = pack["task_manifest"]
    ok &= check("task_manifest hash", manifest_hash == tm["sha256"],
                f"got {manifest_hash[:12]}, want {tm['sha256'][:12]}")

    # 5. Harness: exact pinned version, installed fresh if needed.
    harness = pack["harness"]
    ew_bin = shutil.which("evalwarden")
    venv_dir = work / "venv"
    venv_python = venv_dir / "bin" / "python"
    need_install = True
    if ew_bin and venv_python.exists():
        pass  # venv from a previous verify run is not reused; always fresh
    if need_install:
        if venv_dir.exists():
            shutil.rmtree(venv_dir)
        subprocess.run([sys.executable, "-m", "venv", str(venv_dir)], check=True)
        pip = str(venv_dir / "bin" / "pip")
        subprocess.run([pip, "install", "-q", f"evalwarden=={harness['version']}"],
                       check=True, timeout=600)
        ew_bin = str(venv_dir / "bin" / "evalwarden")
    ver = subprocess.run([str(venv_python), "-c",
                          "import evalwarden; print(evalwarden.__version__)"],
                         capture_output=True, text=True, timeout=30).stdout.strip()
    ok &= check("harness version", ver == harness["version"],
                f"installed {ver}, pinned {harness['version']}")

    # 6. Audit: findings JSON identical (canonical form).
    findings_path = work / "findings.json"
    r = subprocess.run([ew_bin, "audit", str(artifact_dir), "--json", str(findings_path),
                        "--output", str(work / "audit.html")],
                       capture_output=True, text=True, timeout=300)
    findings = json.loads(findings_path.read_text(encoding="utf-8"))
    ar = pack["audit_result"]
    ok &= check("audit_result hash", sha256_bytes(canon_json(findings)) == ar["sha256"],
                f"verdict {findings['verdict']} {findings['score']}/100, "
                f"{len(findings['findings'])} findings")

    # 7. Card: canonical HTML hash identical.
    cards_dir = work / "cards"
    subprocess.run([ew_bin, "report-cards", str(artifact_dir),
                    "--output-dir", str(cards_dir)],
                   check=True, capture_output=True, timeout=300)
    card_files = list(cards_dir.glob("*.html"))
    card_file = next((c for c in card_files if c.name != "index.html"), None)
    if card_file is None:
        ok &= check("card generated", False, "no card html in output dir")
    else:
        card_hash = sha256_bytes(canonicalize_card(
            card_file.read_text(encoding="utf-8")).encode("utf-8"))
        ec = pack["expected_card"]
        ok &= check("expected_card hash", card_hash == ec["sha256"],
                    f"{card_file.name}: got {card_hash[:12]}, want {ec['sha256'][:12]}")

    print()
    print("KILL CRITERION: " + ("PASS -- a stranger regenerated this card from public inputs."
                                if ok else "FAIL -- see failing checks above."))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
